# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            yozel
tagline:          'personal website of a computer nerd'
description:      "I'm a developer, a nerd and a leftist."
url:              https://yozel.co
baseurl:          /

author:
  name:           'Yasin Özel'
  url:            https://twitter.com/yasin_ozel

paginate:         10

gems:
  - jekyll-gist
  - jekyll-paginate

# Custom vars
github:
  profile:           https://github.com/yozel
